name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.1"
        cache: true
    - name: Test
      run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.1"
        cache: true
    - name: Lint
      run: make lint

  e2e-tests:
    runs-on: ubuntu-latest
    services:
      prometheus_1:
        image: prom/prometheus:latest
        # Map port 9091 on the Docker host to port 9090 on the Prometheus container
        ports:
          - 9091:9090
        volumes:
          - test/e2e/prom1/conf:/etc/prometheus
      prometheus_2:
        image: prom/prometheus:latest
        # Map port 9092 on the Docker host to port 9090 on the Prometheus container
        ports:
          - 9092:9090
        volumes:
          - test/e2e/prom2/conf:/etc/prometheus
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.1"
        cache: true
    - name: e2e_test_1
      run: make test-e2e
